import Provider from "./lib/provider";
import "./globals.css";

export const metadata = {
  title: "WrappedUp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
